### PR TITLE
Edit blog page

### PR DESCRIPTION
**Pull request by kalebal**
#28 
This PR creates an 'edit blog post' page.
On this page, there's a list of blog posts (currently dummy data)
Clicking on one opens up a text editor
Hitting save or cancel closes the text editor

It also adds a sneaky link to this page (for dev purposes) on the left-most feature card on the splash page.
Feature cards also wrap on small screens.

### CODE REVIEW

**Review by tetron225 — DISMISSED** [review]
Looks good

**Comment by kalebal** [comment]
The CI is failing because this changes the file name of splashPageContainer to SplashPageContainer to match the rest of the file structure.
Not sure what to do here, any thoughts?

**Review by zkodjo — DISMISSED** [review]
Looks really good

**Review by BillMehlenbacher — APPROVED** [review]
Looks good. Great Job!

**Pull request merged**
