### PR TITLE
Server: Create API routes

### PR DESCRIPTION
**Pull request by zkodjo**
- Creates a new server.js file that's just for the API
- Creates new server script to start the server
- Create skeleton routes for bands, songs, login, and shows
- New migration to add password column
- Fixes for the associatoins
- Created bands controllers (middleware)
- Added logging to config
- Added new script to run API server only

### CODE REVIEW

**Review by kalebal — DISMISSED** [review]
Looks good!

**Comment by kalebal** [comment]
@kodjoz there's some merge conflicts but once those are resolved it's good to go! This is great, thanks for setting it up.

**Comment by zkodjo** [comment]
> @kodjoz there's some merge conflicts but once those are resolved it's good to go! This is great, thanks for setting it up.

Ok I have resolved the conflict - someone needs to review and merge

**Review by kalebal — APPROVED** [review]
Great!

**Review by abachant — APPROVED** [review]

**Pull request merged**
